#!/bin/bash
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT

engkok=$0
REPOKU="https://raw.githubusercontent.com/Genome26/1678/main"
REPOSC="https://raw.githubusercontent.com/Genome26/1678/main"
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
colornow=$(cat /etc/alawivpn/theme/color.conf)
N='\e[0m'
R='\e[1;91m'
G='\e[1;92m'
Y='\e[1;93m'
W='\e[1;97m'
U="$(cat /etc/alawivpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
O="$(cat /etc/alawivpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
ipsaya=$(wget -qO- ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="${REPOKU}/registrasi.txt"

# FUNCTIONKU
garis(){ echo -e " $U$*$N"; }
judul(){ echo -e " $O$*$N"; }
tebal(){ echo -e " $W$*$N"; }
tulis(){ echo -e " $N$*$N"; }
checking_sc() {
    useexp=$(curl -sS "$data_ip" | grep "$ipsaya" | awk '{print $3}')
    if [[ "$date_list" > "$useexp" ]]; then
        systemctl stop nginx
        systemctl stop kyt
        systemctl stop xray
        systemctl stop ws-stunnel
        dilarang
        exit 1
    else
        echo -ne
    fi
}
checking_sc

#!/bin/bash

gogotop() {
    install_gotop() {
        echo "Menginstal gotop..."
        wget https://github.com/cjbassi/gotop/releases/download/3.0.0/gotop_3.0.0_linux_amd64.deb && dpkg -i gotop_3.0.0_linux_amd64.deb && rm -f gotop_3.0.0_linux_amd64.deb
    }

    run_gotop() {
        gotop
    }

    if ! command -v gotop &> /dev/null; then
        install_gotop
    fi

    trap "exec menu" SIGINT
    trap "exec menu" SIGTERM
    trap "exec menu" EXIT

    run_gotop
}

hhtop() {
    trap "exec menu" SIGINT
    trap "exec menu" SIGTERM
    trap "exec menu" EXIT
    htop
}

salahboss() {
    echo -e "  ${R}Salah BOSS!${N}"
    sleep 0.5
    exec $0
}

# MENU HABIS REBOOT/BOOTING
clear
echo
garis "╭════════════════════════════════════════════════════╮"
garis "│${N} ${O}            ◈ MENU UTAMA SAAT BOOTING ◈           ${N}${U} │"
garis "╰════════════════════════════════════════════════════╯"
garis "╭════════════════════════════════════════════════════╮"
garis "│                                                    │"
garis "│ ${W}[${U}01${W}] SSHWS   [${U}02${W}] VMESS   [${U}03${W}] VLESS   [${U}04${W}] TROJAN ${U}│"
garis "│                                                    │"
garis "│ ${W}[${U}05${W}] GOTOP   [${U}06${W}] HTOP    [${U}07${W}] MENU    [${U}08${W}] CLEAN  ${U}│"
garis "│                                                    │"
garis "╰════════════════════════════════════════════════════╯"
echo
echo -ne "  ${W}Pilih ${U}1${W} - ${U}8${W} : "; read input
case $input in
    1) exec m-sshovpn ;;
    2) exec m-vmess ;;
    3) exec m-vless ;;
    4) exec m-trojan ;;
    5) gogotop ;;
    6) hhtop ;;
    7) exec menu2 ;;
    8) exec a ;;
    19) exec pindahmenu ;;
    *) salahboss ;;
esac
exit 0

